name: qr_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pretty_qr_code:
    git: https://github.com/promops/flutter_pretty_qr.git
  mobile_scanner:
    git: https://github.com/juliansteenbakker/mobile_scanner.git
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_animate: ^4.5.0
  awesome_snackbar_content: ^0.1.3
  url_launcher: ^6.2.5
  gap: ^3.0.1
  gal: ^2.3.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf

flutter_launcher_icons:
  image_path_android: "assets/icons/QR_Generator_Icon.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/QR_Generator_Icon_Foreground.png"
  adaptive_icon_monochrome: "assets/icons/QR_Generator_Icon_Monochrome.png"
  min_sdk_android: 21